### ISSUE TITLE
Implement first UI prototype

### ISSUE THREAD

**Issue by Rookfighter** [JeFaProductions/TextAdventure2#1]
Use tkinter.
Containing following elements:
- textfield to enter commands
- textbox for seeing command and story history
- listbox for items

**Comment by JeGa** [comment]
TODO:
- Fix problem with window icon on Linux.
- Add system independent line break.

@Rookfighter this is how it looks currently
![image](https://cloud.githubusercontent.com/assets/530288/18421435/3b9bb9e2-788b-11e6-9981-166162074d71.png)
